### ISSUE TITLE
fa using <i> don't load

### ISSUE THREAD

**Issue by thedannywahl** [eduridden/moodle-theme_elegance#35]
font-awesome icons using ::before selector appear, but icons using &lt;i&gt; don't appear.  The CSS rules don't appear to be loaded for the icon.  See this example of nav icons loaded, but the "top" icon (bottom right) not loaded:

![screen shot 2014-03-11 at 10 10 55 am](https://f.cloud.github.com/assets/743499/2382033/3d2c5cae-a8d5-11e3-9c62-9d09b8df9552.png)

**Comment by gjb2048** [comment]
Hi Danny,

I don't think this is an Elegance or indeed Font Awesome issue, but rather
a Moodle core issue.  I looked into the block show / hide icon and found
that it is the JavaScript that is directly injecting the img tag into the
Dom rather than applying overrideble CSS classes etc.  Therefore it is
impossible to override.  I think either turning JS off or running on a slow
machine where you can see JS doing its job can you see that the icon is
being replaced for its img counterpart.

Gareth

http://about.me/gjbarnard

**Comment by eduridden** [comment]
I also cant replicate what you are describing and have to concur with Gareth at this point until we have more evidence otherwise. Please feel free to reopen this if you can add more info Otherwise I am closing for now.

**Comment by thedannywahl** [comment]
moodle doesn't like including a CSS stylesheet with a dot and three character extension in a config.  The file gets included, but not really- it shows up as a blank file with no CSS rules.

so rename font-awesome.min.css to 'font-awesome.css'  and change config.php to load 'font-awesome' instead of 'font-awesome.min' and it'll work ;)

this is probably a Moodle bug, but I'll have to test it out. The above is a work around for this theme to get font-awesome working.
