### ISSUE TITLE
Blatant rip off - not cool

### ISSUE THREAD

**Issue by benbull** [eduridden/moodle-theme_elegance#62]
This theme is a blatant copy of http://learningspace.falmouth.ac.uk, you've even ripped the assets - shame on you!

Not even a nod or attribution to the team at Falmouth who created it!

**Comment by mpuusaar** [comment]
Dear Ben,

Could you please explain your accusations towards moodleman? As far as I can tell, both of these themes use Moodle Clean and Bootstrap themes as templates to build upon and thus inherit some similar designs mostly because websites built with the help of Bootstrap always look similar ;)
Is there somewhere where we could see the theme code used for http://learningspace.falmouth.ac.uk site so that a objective comparison could be made? Is it https://github.com/aaronmarruk/LearningspaceTheme?

Thanks for pointing out your concerns, but please be more concrete on your statements.

**Comment by benbull** [comment]
No, that's not the code base of Aarons theme.  The dead give away for me is the identical image assets used when Aaron launched the theme are present in this repo but were altered 3 months ago by moodleman.
On Thu, Apr 03, 2014 at 5:01 pm, mpuusaar notifications@github.com wrote:Dear Ben,

Could you please explain your accusations towards moodleman? As far as I can tell, both of these themes use Moodle Clean and Bootstrap themes as templates to build upon and thus inherit some similar designs mostly because websites built with the help of Bootstrap always look similar ;)
Is there somewhere where we could see the theme code used for http://learningspace.falmouth.ac.uk site so that a objective comparison could be made? Is it https://github.com/aaronmarruk/LearningspaceTheme?

Thanks for pointing out your concerns, but please be more concrete on your statements.

**Comment by mpuusaar** [comment]
Thanks for your reply. Can you give us direct links to Aarons original work that is supposedly being copied by moodleman.

**Comment by benbull** [comment]
Aaron will have to do that as it's in an enterprise repo. I'm sure it will be forthcoming.

**Comment by eduridden** [comment]
Hello all,

Thought it important I jump in here and explain what is happening.

YES! Aaron's site was inspiration for the theme design. No-one can deny the many similar aspects of the the them that mirror his design. I sent three emails to Aaron over the past months since Elegance's release to which I had no response and just went with a launch.

NO! There are no shared assets or shared code between the themes. The code is, as described earlier, Bas's Bootstrap 3 code with my own css and assets. But they ARE based on Aaron's design ideas.

If you look at the readme (https://github.com/moodleman/moodle-theme_elegance/blob/master/README.md) I have always been very keen to recognise all who had any input into this theme and I am more than happy to add Aaron as his site design was highly influential. 

I am hoping if someone can reach Aaron, as I have not had any luck, and have him contact me I would be very keen to ensure all credit is made.

I have been working in Moodle for 10 years and would hate my final project here to be the most contentious.

Julian

**Comment by benbull** [comment]
I've sent this to Aaron in the hope he replies to you.  I'm still not convinced about your assertion of no shared assets as the history of these images;

https://github.com/moodleman/moodle-theme_elegance/tree/master/pix/bg/loginbg_samples

Shows that there are identical in naming, and content, of those used by Aaron during development and at initial release.  

How can these be identical if you didn't rip any assets?

**Comment by benbull** [comment]
This illustrates the original assets used and the changes;

https://github.com/moodleman/moodle-theme_elegance/commit/697835c825e9a9a7f042cec8cdf89170f3947a99

**Comment by ghost** [comment]
Hello, just to clear up, the examples that Ben has provided aren't present in any Learning Space repo that predates a commit in the Elegance repo.

However, the assets can be seen in a cached version of Learning Space, dating October 2013: http://web.archive.org/web/20131031192855/http://learningspace.falmouth.ac.uk/login/index.php

We do have much better examples assets and code being used, but I have been asked by my line manager not to comment further at this point in time.

**Comment by DBezemer** [comment]
@benbull with the image assets I would predict that Aaron has the same issues there, as the images are not his original work either. Using TinEye you can see that these images are all across the web, and definitely not Aaron's original works. As Julian stated he was inspired by (parts) of the design, but code and assets are not the original works of Aaron.

If attribution is required, I'm sure there is no problem with giving attribution to the design ideas as Julian already stated that he tried to contact Aaron. I am suspecting that Aaron is @aaronmarruk so I suggest opening a constructive dialogue.

**Comment by benbull** [comment]
@DBezemer partially agree with that, however they had the same names, in the same order, implemented in the same way.....

Seems like @aaronmarruk has been gagged by his manager so I'm going to duck out of this now as it's very much up to Aaron to provide the proof of his above comment if he's allowed by his employer.

'Inspired by' and ripping code are two very different things as I'm sure you agree - and it's difficult to pull that apart in this situation given the constraints and use of common code libraries, however the lack of attribution despite @moodleman 's admission he did use @aaronmarruk 's work as inspiration leaves me very cold.  I know he tried to contact, but even with the lack of response he still should have given a decent attribution.

**Comment by oscott** [comment]
Hi @moodleman - You can speak with Aaron on github, he's already commented on this over at #60 

Beyond the code and asset similarity, this is problematic for me in that the ["idea of the theme ... look as little like Moodle"](https://moodle.org/plugins/view.php?plugin=theme_elegance) that you are taking credit for, is the outcome of a lengthly design process using various open-source elements and contributed code. Work achieved by Aaron in consultation with various teams around the university. 

Whilst there is contention regarding certain elements of the design and code, We are seeking a positive outcome where the work is referenced appropriately. It is good that you have recognised here the inspiration for your theme. However, I guess the question is, was it 'inspired by' or 'based on'?

**Comment by ghost** [comment]
Credit has now been given in the README here: https://github.com/moodleman/moodle-theme_elegance
